# Generated by Django 6.0.3 on 2026-03-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postcomments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcomments',
            unique_together=set(),
        ),
    ]
