# Generated by Django 6.0.3 on 2026-03-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
